### ISSUE TITLE
Remove setting NewEncoder when NEW_ENCODER env is set to empty

### ISSUE THREAD

**Issue by padlar** [statnett/controller-runtime-viper#51]
I think we should create an issue to follow up on this. If setting it to nil, the test fails:

````
Summarizing 1 Failure:
  [FAIL] Zap log level flag options setup with zap-encoding flag provided [It] Should default to json encoder when not set [encoder]
  /home/erikbo/projects/github/controller-runtime-viper/pkg/zap/zap_test.go:241
````

_Originally posted by @erikgb in https://github.com/statnett/controller-runtime-viper/pull/49#discussion_r1055322165_

**Comment by erikgb** [comment]
I think this was fixed by https://github.com/statnett/controller-runtime-viper/pull/82.
